<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\MyPersonalTool.Sdk\MyPersonalTool.Sdk.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <Target Name="CopyToPlugins" AfterTargets="Build" Condition="'$(Configuration)'=='Debug'">
    <Copy SourceFiles="$(OutputPath)$(AssemblyName).dll"
          DestinationFolder="..\..\MyPersonalTool\bin\Debug\net9.0\plugins" />
  </Target>

</Project>
